apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: pramodksahoo/test
          ports:
            - containerPort: 8280

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    name: test-service
spec:
  ports:
    - port: 80
      targetPort: 8280
      protocol: TCP
  selector:
    app: test
  type: ClusterIP
